---
image:
  repository: gcr.io/jendevops1/brb
pagespeed:
  enabled: false

openresty:
  geoip:
    enabled: false
    accountid: ""
    license: ""
  cloudflare:
    enabled: false

ingress:
  enabled: true
  metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
