---
image:
  repository: gcr.io/jendevops1/brb
pagespeed:
  enabled: false

openresty:
  geoip:
    enabled: false
    accountid: ""
    license: ""
  cloudflare:
    enabled: false

ingress:
  enabled: true
