---
hostname: jencub.xyz
ingress:
  metadata:
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/issuer: "letsencrypt-prod"
  spec:
    tls:
      - hosts:
          - jencub.xyz
        secretName: tls-jencub-xyz
image:
  tag: develop
